version: "3.7"

services:
  ipfspodcasting-docker:
    environment:
      - useremail=do@bobot.lol
    image: ipfspodcasting/podcastnode:v0.6d
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - 4001:4001/tcp  # IPFS nat this port
      - 5001:5001/tcp  # IPFS  http://....:4001/webui
      - 8675:8675/tcp  # Web UI
    volumes:
      - ./ipfs:/ipfs-podcasting/ipfs
      - ./cfg:/ipfs-podcasting/cfg
