version: "3.7"

services:
  ipfspodcasting-docker:

    build:
      context: .
      args:
        USERID: '1000'
        TARGETARCH: 'amd64'
        IPFSGO: 'v0.13.0'
    env_file:
      - .env
    entrypoint: /bin/bash -c 'chown -R ${USERID} ipfs/ && python ipfspodcastnode.py'
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "${USERID}:users"
    ports:
      - 4001:4001/tcp  # IPFS nat this port
      - 4001:4001/udp  # IPFS nat this port
      - 5001:5001/tcp  # IPFS  http://....:5001/webui
      - 8675:8675/tcp  # IPFSPodcasting Web UI
    volumes:
      - ./ipfs:/ipfs-podcasting/ipfs
      - ./cfg:/ipfs-podcasting/cfg
